
```{r}
dep <- c("Dependency", "Adjacency") 
block <- c("Block 1-2", "Block 2-3", "Block 3-4", "Block 4-5", "Block 5-6", "Block 6-7")
coln <- c(dep, block)
for(bl in block){
  coln <- c(coln, paste(dep, bl, sep = " * "))
}

samps_adults <- read_csv("../Adults/stanout/shifted_lognormal_impl_learning_adults_posterior.csv")
samps_adults$group <- "Adults"
samps_children <- read_csv("../Children/stanout/shifted_lognormal_impl_learning_children_posterior.csv")
samps_children$group <- "Children"

samps <- bind_rows(samps_adults, samps_children)

samps_rt <- samps %>%
  as_tibble() %>%
  mutate_at(vars(starts_with("b_COND"), "b_scaletrial_in_block"), list(~ (exp(b_Intercept + .) - exp(b_Intercept)))) %>%
  mutate_at(vars(ends_with("Intercept")), exp)

names(samps_rt) <- c("(Intercept)", "Non-decision time", coln, "Repetition within block", "Group")
predlevels <- c("(Intercept)", coln, "Repetition within block", "Non-decision time")

samps_rt_summary <- samps_rt %>%  
  pivot_longer(cols = -Group, names_to = "param", values_to = "value") %>%
  mutate(param = factor(param, levels = predlevels, ordered = T)) %>%
  #select(param) %>% unique() %>% pull(param)
  group_by(param, Group) %>%
  summarise(Med = dmode(value),
            Lo = rethinking::HPDI(value, prob = .95)[1],
            Up = rethinking::HPDI(value, prob = .95)[2],
            p = mean(value < 0 )) %>%
  ungroup() %>%
  mutate_at(vars(Med, Lo, Up), round, 0) %>%
  mutate_at(vars(p), round, 3) %>%
  mutate(p = ifelse(p == 0, 0.001, 
                    ifelse(p == 1, 0.999, p)),
    p = as.character(as.numeric(paste0(p))),
    p = gsub("0\\.", ".", p),
    p = replace(p, p == ".001", "<.001"),
    p = replace(p, p == ".999", ">.999")) %>%
  unite(Lo:Up, col = "PI", sep = ", ") %>%
  mutate(PI = paste0("[", PI, "]"))


```


```{r, results = 'asis'}
samps <- samps_rt_summary %>% pivot_wider(names_from = Group, values_from = Med:p) %>%
  dplyr::select(param, ends_with("Adults"), ends_with("Children")) %>%
  filter(param != "Non-decision time")
#samps_adults <- filter(samps_rt_summary, Group == "Adults") %>% dplyr::select(-Group)
names(samps) <- c("Predictor", rep(c("$\\hat{\\mu}$", "95\\% HPDI", "$P(\\hat{\\mu}<0)$"), 2))
papaja::apa_table(samps,
                  align = c(rep("l", 1), rep("r", 6)), 
                  escape = FALSE, 
                  longtable = TRUE,
                  placement = "ht",
                  font_size = "small", 
                  col_spanners = list(`Experiment 1: Adults` = c(2,4),
                                      `Experiment 2: Children` = c(5,7)),
                  note = "$\\hat{\\mu}$ indicates the most probable \\textit{a posteriori} parameter value. 95\\% HPDI is the range containing 95\\% of the posterior probability mass. $P(\\hat{\\mu}<0)$ is the posterior probability that the true parameter value is smaller than 0. '*' indicates interactions.",
                  digits = 0,
                  caption = "\\label{tab:fixedeffects}Fixed effects summary of the models fitted for the response-time data of Experiment 1 and Experiment 2. Shown are the estimated effects for Adjacency (levels: adjacent, nonadjacent), Dependency (levels: dependency, baseline), Block (levels: 1-7), and all by-Block 2-way interactions with Dependency and Adjacency. Effects summarised by its most probable parameter value $\\hat{\\mu}$ with 95\\% HPDIs are shown in msecs.")
```



```{r fig.width=8, fig.height=7}
plot <- samps_rt %>%  
  pivot_longer(cols = -Group, names_to = "param", values_to = "value") %>%
  mutate(param = factor(param, levels = predlevels, ordered = T)) %>%
  #select(param) %>% unique() %>% pull(param)
  group_by(param, Group) %>%
  summarise(Med = dmode(value),
            Lo = rethinking::HPDI(value, prob = .95)[1],
            Up = rethinking::HPDI(value, prob = .95)[2],
            p = mean(value < 0 )) %>%
  ungroup() %>%
  filter(param != "Non-decision time") %>%
  mutate(param = factor(param, levels = rev(predlevels), ordered = T)) %>%
  ggplot(aes(y = Med, x = param, ymin = Lo, ymax = Up)) +
  geom_errorbar(width = .25, color = "darkred") +
  geom_point(size = 2) +
  coord_flip() +
  ggthemes::theme_few(base_size = 12) +
  geom_hline(yintercept = 0, linetype = "dotted", color = "grey10") +
  facet_grid(~Group) +
  # scale_y_continuous(breaks = seq(-600, 600, by = 200)) +
  theme(axis.title.y = element_text(angle = 360),
        strip.text = element_text(hjust = 0, face = "bold")) +
  labs(y = "Most probable parameter value\nwith 95% HPDI (in msecs)",
       x = "Predictor") 

ggsave("modelsummary.png", width = 8, height = 6)
```

